---
title: "HW2"
output: html_document
date: "2023-05-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Breakdown

```{r}
library(qeML)
data(pef)
data <- pef
Name <- 'wkswrkd'
numCuts <- 4
head(data)
```

```{r}
if (!is.numeric(data[,Name])){
  stop("data must be numeric, call form: cutN(data, categoryName, numCuts)")
}
df <- data[order(data[,Name]),,drop=FALSE]  # order by wkswrkd
size <- length(df[,Name])        # numrows = 20090
intervalSize <- ceiling(df[size, Name]/ numCuts) # size 13 for splitting min:max 0:52 wkswrkd into 4 categories
iVal <- intervalSize
head(df)
```

```{r}
cutPoints <- c(1)
for (i in 1:numCuts){           # 1:4 groups of wkswrkd
  val <- match(iVal, df[,Name]) # find group cutoff (i.e. 13) index
  if (is.na(val)){              # if no match, find closest neighbor index (min)
    val <- which.min(abs(df[,Name] - iVal)) 
  }
  if (i == numCuts){            # for last group: add last row index to index list, exit
    cutPoints <- append(cutPoints, size)
    break
  }
  cutPoints <- append(cutPoints, val) # add last row index to index list
  iVal <- iVal + intervalSize         # i.e. 13+13 -> 26+13 -> 39+13 -> 52
}
print(cutPoints)                # print indices of cutoffs
print(numCuts)
```

```{r}
df$newFactors <- ""
for (i in 1:numCuts) {
  first <- df[cutPoints[i], Name]      # min of range (i.e. 13 wkswrkd)
  second <-df[cutPoints[i+1], Name]    # max of range (i.e. 26 wkswrkd)
  label <- paste("(", first, ", ", second, "]", sep = "") # i.e. "(13, 26]"
  indexMin <- cutPoints[i]             # index of min (i.e. 1643)
  indexMax <- cutPoints[i+1]           # index of max (i.e. 2310)
  df$newFactors[indexMin:indexMax] <- label
}
df$newFactors <- as.factor(df$newFactors)
print(unique(df$newFactors))
head(df)
#return(df$newFactors)
```

```{r}
df <- df[order(as.numeric(row.names(df))), ]
head(df)
```

### Function

```{r}
library(qeML)
data(pef)

Ncut <- function(data, Name, numCuts=2){
  if (!is.numeric(data[,Name])){
    stop("data must be numeric, call form: cutN(data, categoryName, numCuts)")
  }
  df <- data[order(data[,Name]),,drop=FALSE]  # order by wkswrkd, keep original row indices to sort later
  size <- length(df[,Name])                   # numrows = 20090
  intervalSize <- ceiling(df[size, Name]/ numCuts) # interval size 13 for splitting min:max 0:52 wkswrkd into 4 categories
  iVal <- intervalSize
  cutPoints <- c(1)
  for (i in 1:numCuts){                       # 1:4 groups of wkswrkd
    val <- match(iVal, df[,Name])             # find group cutoff (i.e. 13) index
    if (is.na(val)){                          # if no match, find closest neighbor index (min)
      val <- which.min(abs(df[,Name] - iVal)) 
    }
    if (i == numCuts){                        # for last group: add last row index to index list, exit
      cutPoints <- append(cutPoints, size)
      break
    }
    cutPoints <- append(cutPoints, val)       # add last row index to index list
    iVal <- iVal + intervalSize               # i.e. 13+13 -> 26+13 -> 39+13 -> 52
  }
  print(cutPoints)                            # print indices of cutoffs
  df$newFactors <- ""
  for (i in 1:numCuts) {
    first <- df[cutPoints[i], Name]           # min of range (i.e. 13 wkswrkd)
    second <-df[cutPoints[i+1], Name]         # max of range (i.e. 26 wkswrkd)
    label <- paste("(", first, ", ", second, "]", sep = "") # i.e. "(13, 26]"
    indexMin <- cutPoints[i]                  # index of min (i.e. 1643)
    indexMax <- cutPoints[i+1]                # index of max (i.e. 2310)
    df$newFactors[indexMin:indexMax] <- label # add range label to new column
  }
  df$newFactors <- as.factor(df$newFactors)   # convert to factor
  print(unique(df$newFactors))
  df <- df[order(as.numeric(row.names(df))),] # sort using original order
  return(df$newFactors)
}

data$wkswrkdCategory <- Ncut(pef, 'wkswrkd', 4) # test!
head(data)
```
