---
title: "HW3md"
output: html_document
date: "2023-05-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(qeML)
library(fairml)
library(dplyr)
library(ggplot2)
data(compas)
compas$two_year_recid <- as.numeric(compas$two_year_recid == 'Yes')

data <- compas
yName <- 'two_year_recid'
sName <- 'race'
xName <- 'age'
condits <- c('priors_count <= 4','decile_score >= 6')
qeFtn <- qeKNN
minS <- 50
yLim <- NULL
useLoess <- TRUE
```

**Apply conditions to data**

```{r}
data <- compas
for (i in 1:length(condits)) { 
  condit <- paste("data[which(data$",condits[i],"),]",sep="")
  expr <- parse(text=condit)
  data <- eval(expr)
} # IT WORKS
```

**Train qeFtn on data**

```{r}
model <- qeFtn(data,yName)
```

**Get recidivism/y probabilities for each age**

TODO: add sLim condition, eliminate races with less than 50 ppl

```{r}
data <- data[order(data$xCat),]
dataLen <- length(data[[xName]])                # number rows
uniqueXNum <- length(unique(data[[xName]]))     # number unique x values (i.e. ages)

useUnique <- TRUE
data$xCats <- data[[xName]]
data$sCats <- data[[sName]]

xCats <- unique(data$xCats)
xRng <- max(xCats) - min(xCats)
sCats <- unique(data[,sName])
n <- length(sCats)
allPreds <- vector("list",n)
allCats <- vector("list",n)

# TODO: add sLim condition, eliminate races with less than 50 ppl

# Subset for each race
for (i in 1:length(sCats)) {
  s <- sCats[i]
  sSubset <- data[which(data$sCats == s),]
  predList <- c() # collect predictions for race
  catsList <- c() # collect ages corresponding to predictions for race

  # Find all ages which appear in a particular race
  xCats <- unique(sSubset$xCats)
  for (j in 1:length(xCats)) {
    xCat <- xCats[j]
    xsSubset <- sSubset[which(sSubset$xCats==xCat),]
    xsSubset <- xsSubset[,!(names(xsSubset) %in% c('sCats','xCats',yName))]
    
    # Collect recidivism prediction for each age in the race group
    if (nrow(xsSubset) > 0) {
      sPreds <- predict(model, xsSubset)
      sPredsList <- sPreds[1,]
      avgSPreds <- mean(sPredsList)
      predList <- c(predList,avgSPreds)
      catsList <- c(catsList,xCat)
    }
  }
  allPreds[[i]] <- predList
  allCats[[i]] <- catsList
}
```

**Ggplot: Hard-Coded**

TODO: add race labels

```{r}
plotdf1 <- data.frame(allCats[[1]],allPreds[[1]])
plotdf2 <- data.frame(allCats[[2]],allPreds[[2]])
plotdf3 <- data.frame(allCats[[3]],allPreds[[3]])
plotdf4 <- data.frame(allCats[[4]],allPreds[[4]])
plotdf5 <- data.frame(allCats[[5]],allPreds[[5]])
plotdf6 <- data.frame(allCats[[6]],allPreds[[6]])

colnames(plotdf1) <- c('cats','preds')
colnames(plotdf2) <- c('cats','preds')
colnames(plotdf3) <- c('cats','preds')
colnames(plotdf4) <- c('cats','preds')
colnames(plotdf5) <- c('cats','preds')
colnames(plotdf6) <- c('cats','preds')

ggplot() +
  geom_smooth(data=plotdf1, color="#FF0000", 
              mapping=aes(x=cats, y=preds),se=F)+
  geom_smooth(data=plotdf2, color="orange", 
              mapping=aes(x=cats, y=preds),se=F)+
  geom_smooth(data=plotdf3, color="yellow", 
              mapping=aes(x=cats, y=preds),se=F)+
  geom_smooth(data=plotdf4, color="green", 
              mapping=aes(x=cats, y=preds),se=F)+
  geom_smooth(data=plotdf5, color="blue", 
              mapping=aes(x=cats, y=preds),se=F)+
  geom_smooth(data=plotdf6, color="purple", 
              mapping=aes(x=cats, y=preds),se=F)
```

**Ggplot: Using Eval**

TODO: Add race category labels in a legend

```{r}
# For each s category
for (i in 1:length(sCats)) {
  eval(parse(text=paste("plotdf",i," <- data.frame(allCats[[",i,"]],allPreds[[",i,"]])",sep="")))
  eval(parse(text=paste("colnames(plotdf",i,") <- c('cats','preds')",sep="")))
}

# Get list of unique, distinct colors for plot
colorList <- rainbow(length(sCats))

exec <- "ggplot() + \n"
for (i in 1:length(sCats)) {
  col <- colorList[i]
  if (i < length(sCats)) {
    exec <- paste(exec,"geom_smooth(data=plotdf",i,",color='",col,
                  "',mapping=aes(x=cats, y=preds),se=F) + \n",sep="")
  } else {
    exec <- paste(exec,"geom_smooth(data=plotdf",i,",color='",col,
                  "',mapping=aes(x=cats, y=preds),se=F) \n",sep="")
  }
}

#cat(exec)
eval(parse(text=exec))
```

**Base R Plotting: Just the Points**

```{r}
plot(allCats[[1]], allPreds[[1]], col="red", xlab="Age", ylab="Recidivism Probability")
points(allCats[[2]], allPreds[[2]], col="orange")
points(allCats[[3]], allPreds[[3]], col="yellow")
points(allCats[[4]], allPreds[[4]], col="green")
points(allCats[[5]], allPreds[[5]], col="blue")
points(allCats[[6]], allPreds[[6]], col="purple")
```
